<?php

namespace App\Services\ExerciseCatalog;

use Illuminate\Filesystem\Filesystem;
use JsonException;

class IOSExerciseCatalogExporter
{
    public function __construct(private Filesystem $files) {}

    /**
     * @param  array<string, mixed>  $catalog
     *
     * @throws JsonException
     */
    public function export(array $catalog, string $directory): void
    {
        /** @var list<array<string, mixed>> $exercises */
        $exercises = $catalog['exercises'] ?? [];

        $this->files->ensureDirectoryExists($directory);
        $this->files->put("{$directory}/Exercise.swift", $this->exerciseFile($exercises));
        $this->files->put("{$directory}/ExerciseCatalog.swift", $this->catalogFile($exercises));
    }

    /**
     * @param  list<array<string, mixed>>  $exercises
     */
    private function exerciseFile(array $exercises): string
    {
        $cases = implode("\n", array_map(
            fn (array $exercise): string => '    case '.$exercise['id'],
            $exercises,
        ));

        return "// Generated by `php artisan app:export-exercise-catalog --ios`. Do not edit.\n"
            ."import Foundation\n\n"
            ."public enum Exercise: String, Codable, CaseIterable, Sendable {\n"
            .$cases."\n"
            ."}\n\n"
            .<<<'SWIFT'
        public extension Exercise {
            var englishName: String {
                ExerciseCatalog.metadata(for: self).englishName
            }

            var category: ExerciseCategory {
                ExerciseCatalog.metadata(for: self).category
            }

            var metadata: ExerciseMetadata {
                ExerciseCatalog.metadata(for: self)
            }

            var trackingMode: ExerciseTrackingMode {
                metadata.trackingMode
            }

            var targetMetrics: Set<ExerciseTargetMetric> {
                metadata.targetMetrics
            }

            var supportsExternalLoad: Bool {
                category == .strength || metadata.supportsExternalLoad
            }

            func remoteImage(gender: Gender = .female) -> URL? {
                Supabase.url(folder: "vertical", for: "\(rawValue)_\(gender.rawValue)", fileExtension: "jpeg")
            }

            func remoteTutorialImage(gender: Gender = .female) -> URL? {
                Supabase.url(folder: "tutorial", for: "\(rawValue)_\(gender.rawValue)", fileExtension: "png")
            }
        }
        SWIFT;
    }

    /**
     * @param  list<array<string, mixed>>  $exercises
     */
    private function catalogFile(array $exercises): string
    {
        $definitions = implode(",\n", array_map(
            fn (array $exercise): string => $this->definition($exercise),
            $exercises,
        ));

        return <<<SWIFT
        // Generated by `php artisan app:export-exercise-catalog --ios`. Do not edit.
        import Foundation

        public enum ExerciseCatalog {
            nonisolated(unsafe) public static let definitions: [Exercise: ExerciseMetadata] = [
        {$definitions}
            ]

            public static func metadata(for exercise: Exercise) -> ExerciseMetadata {
                guard let metadata = definitions[exercise] else {
                    preconditionFailure("Missing metadata for exercise \\(exercise.rawValue)")
                }

                return metadata
            }

            public static func relevantExercises(
                availableEquipment: [Equipment],
                goal: Goal,
                restrictions: [MovementRestriction],
                trainingLevel: TrainingLevel
            ) -> [ExerciseMetadata] {
                let availableEquipmentSet = Set(availableEquipment)
                let restrictionsSet = Set(restrictions)

                return Exercise.allCases
                    .map { metadata(for: $0) }
                    .filter {
                        $0.isCompatible(
                            withAvailableEquipment: availableEquipmentSet,
                            goal: goal,
                            restrictions: restrictionsSet,
                            trainingLevel: trainingLevel
                        )
                    }
                    .sorted { lhs, rhs in
                        if lhs.category.englishName != rhs.category.englishName {
                            return lhs.category.englishName < rhs.category.englishName
                        }

                        return lhs.englishName < rhs.englishName
                    }
            }
        }
        SWIFT;
    }

    /**
     * @param  array<string, mixed>  $exercise
     *
     * @throws JsonException
     */
    private function definition(array $exercise): string
    {
        $stringList = fn (string $key): string => $this->swiftStringArray($exercise[$key] ?? []);
        $set = fn (string $key): string => $this->swiftSet($exercise[$key] ?? []);
        $notesForLlm = $exercise['notesForLlm'] === null
            ? 'nil'
            : $this->swiftString((string) $exercise['notesForLlm']);

        return sprintf(<<<'SWIFT'
                .%s: ExerciseMetadata(
                    exercise: .%s,
                    englishName: %s,
                    category: .%s,
                    requiredEquipment: %s,
                    compatibleGoals: %s,
                    movementPatterns: %s,
                    difficulty: .%s,
                    isUnilateral: %s,
                    isPerSideLoad: %s,
                    contraindicatedRestrictions: %s,
                    substitutionCandidates: %s,
                    userDescription: %s,
                    instructions: %s,
                    tips: %s,
                    primaryMuscles: %s,
                    secondaryMuscles: %s,
                    supportsExternalLoad: %s,
                    trackingMode: .%s,
                    targetMetrics: %s,
                    metValue: %s,
                    notesForLLM: %s
                )
SWIFT,
            $exercise['id'],
            $exercise['id'],
            $this->swiftString((string) $exercise['name']),
            $exercise['category'],
            $set('requiredEquipment'),
            $set('compatibleGoals'),
            $set('movementPatterns'),
            $exercise['difficulty'],
            $exercise['isUnilateral'] ? 'true' : 'false',
            $exercise['isPerSideLoad'] ? 'true' : 'false',
            $set('contraindicatedRestrictions'),
            $this->swiftExerciseArray($exercise['substitutionCandidates'] ?? []),
            $this->swiftString((string) $exercise['description']),
            $stringList('instructions'),
            $stringList('tips'),
            $set('primaryMuscles'),
            $set('secondaryMuscles'),
            $exercise['supportsExternalLoad'] ? 'true' : 'false',
            $exercise['trackingMode'],
            $set('targetMetrics'),
            $this->swiftNumber($exercise['metValue']),
            $notesForLlm,
        );
    }

    /**
     * @throws JsonException
     */
    private function swiftString(string $value): string
    {
        return json_encode($value, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

    /**
     * @throws JsonException
     */
    private function swiftStringArray(mixed $values): string
    {
        return '['.implode(', ', array_map(
            fn (mixed $value): string => $this->swiftString((string) $value),
            is_array($values) ? $values : [],
        )).']';
    }

    private function swiftSet(mixed $values): string
    {
        return 'Set(['.implode(', ', array_map(
            fn (mixed $value): string => '.'.(string) $value,
            is_array($values) ? $values : [],
        )).'])';
    }

    private function swiftExerciseArray(mixed $values): string
    {
        return '['.implode(', ', array_map(
            fn (mixed $value): string => '.'.(string) $value,
            is_array($values) ? $values : [],
        )).']';
    }

    private function swiftNumber(mixed $value): string
    {
        return number_format((float) $value, 1, '.', '');
    }
}
