<?php

namespace App\Services\ExerciseCatalog;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class PHPExerciseCatalogExporter
{
    public function __construct(private Filesystem $files) {}

    /**
     * @param  array<string, mixed>  $catalog
     */
    public function export(array $catalog, string $directory): void
    {
        /** @var list<array{id: string, name: string}> $majorMuscleGroups */
        $majorMuscleGroups = $catalog['referenceData']['majorMuscleGroups'] ?? [];
        /** @var list<array{id: string, name: string, majorGroup: string}> $muscleGroups */
        $muscleGroups = $catalog['referenceData']['muscleGroups'] ?? [];

        $this->files->ensureDirectoryExists($directory);
        $this->files->put("{$directory}/MajorMuscleGroup.php", $this->majorMuscleGroupFile($majorMuscleGroups));
        $this->files->put("{$directory}/MuscleGroup.php", $this->muscleGroupFile($muscleGroups));
    }

    /** @param list<array{id: string, name: string}> $groups */
    private function majorMuscleGroupFile(array $groups): string
    {
        $cases = collect($groups)->map(fn (array $group): string => '    case '.Str::studly($group['id'])." = '{$group['id']}';")->implode("\n");

        return "<?php\n\nnamespace App\\Enums\\Generated;\n\n// Generated by `php artisan app:export-exercise-catalog --php`. Do not edit.\nenum MajorMuscleGroup: string\n{\n{$cases}\n}\n";
    }

    /** @param list<array{id: string, name: string, majorGroup: string}> $groups */
    private function muscleGroupFile(array $groups): string
    {
        $cases = collect($groups)->map(fn (array $group): string => '    case '.Str::studly($group['id'])." = '{$group['id']}';")->implode("\n");
        $matches = collect($groups)->map(fn (array $group): string => '            self::'.Str::studly($group['id']).' => MajorMuscleGroup::'.Str::studly($group['majorGroup']).',')->implode("\n");

        return "<?php\n\nnamespace App\\Enums\\Generated;\n\n// Generated by `php artisan app:export-exercise-catalog --php`. Do not edit.\nenum MuscleGroup: string\n{\n{$cases}\n\n    public function majorGroup(): MajorMuscleGroup\n    {\n        return match (\$this) {\n{$matches}\n        };\n    }\n}\n";
    }
}
