<?php

/*
|--------------------------------------------------------------------------
| AI Model Pricing
|--------------------------------------------------------------------------
|
| USD per million tokens, used to cost recorded AI usage. Generated by
| `php artisan app:sync-ai-pricing` from https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json
| Last synced: 2026-10-09. Re-run the command after changing an agent's model.
|
*/

return [

    'models' => [
        'gemini' => [
            'gemini-2.5-flash' => ['input' => 0.3, 'output' => 2.5, 'cache_read' => 0.03],
            'gemini-2.5-flash-lite' => ['input' => 0.1, 'output' => 0.4, 'cache_read' => 0.01],
            'gemini-2.5-pro' => ['input' => 1.25, 'output' => 10.0, 'cache_read' => 0.125],
            'gemini-3.1-pro-preview' => ['input' => 2.0, 'output' => 12.0, 'cache_read' => 0.2],
            'gemini-3.5-flash' => ['input' => 1.5, 'output' => 9.0, 'cache_read' => 0.15],
            'gemini-3.5-flash-lite' => ['input' => 0.3, 'output' => 2.5, 'cache_read' => 0.03],
            'gemini-3.6-flash' => ['input' => 0.75, 'output' => 3.75, 'cache_read' => 0.075],
            'gemini-3.7-flash' => ['input' => 0.75, 'output' => 3.75, 'cache_read' => 0.075],
            'gemini-3.8-flash' => ['input' => 0.75, 'output' => 3.75, 'cache_read' => 0.075],
            'gemini-flash-latest' => ['input' => 0.75, 'output' => 3.75, 'cache_read' => 0.075],
            'gemini-flash-lite-latest' => ['input' => 0.3, 'output' => 2.5, 'cache_read' => 0.03],
            'gemini-pro-latest' => ['input' => 2.0, 'output' => 12.0, 'cache_read' => 0.2],
        ],
        'openai' => [
            'gpt-5-mini' => ['input' => 0.25, 'output' => 2.0, 'cache_read' => 0.025],
            'gpt-5-nano' => ['input' => 0.05, 'output' => 0.4, 'cache_read' => 0.005],
            'gpt-5.4-mini' => ['input' => 0.75, 'output' => 4.5, 'cache_read' => 0.075],
            'gpt-5.5' => ['input' => 5.0, 'output' => 30.0, 'cache_read' => 0.5],
            'gpt-5.6' => ['input' => 4.0, 'output' => 20.0, 'cache_read' => 0.4, 'cache_write' => 5.0],
            'gpt-5.6-luna' => ['input' => 0.2, 'output' => 1.2, 'cache_read' => 0.02, 'cache_write' => 0.25],
            'gpt-5.6-sol' => ['input' => 4.0, 'output' => 20.0, 'cache_read' => 0.4, 'cache_write' => 5.0],
            'gpt-5.6-terra' => ['input' => 2.0, 'output' => 12.0, 'cache_read' => 0.2, 'cache_write' => 2.5],
            'gpt-6-astra' => ['input' => 10.0, 'output' => 50.0, 'cache_read' => 1.0, 'cache_write' => 12.5],
            'gpt-6-luna' => ['input' => 0.1, 'output' => 0.5, 'cache_read' => 0.01, 'cache_write' => 0.125],
            'gpt-6-sol' => ['input' => 2.0, 'output' => 10.0, 'cache_read' => 0.2, 'cache_write' => 2.5],
            'gpt-6.1-sol' => ['input' => 2.0, 'output' => 10.0, 'cache_read' => 0.1, 'cache_write' => 2.5],
        ],
    ],

];
